export const SET_NEWS_DETAIL="SET_NEWS_DETAIL"

export const SET_REFRESH="SET_REFRESH"

export const SET_HOT_NEWS="SET_HOT_NEWS"

export const SET_GUESS_NEWS="SET_GUESS_NEWS"

export const SET_FAVOURITE_NEWS="SET_FAVOURITE_NEWS"

export const SET_HISTORY_NEWS="SET_HISTORY_NEWS"